### PR TITLE
Add parse for voice

### PR DESCRIPTION
**Pull request by xtao**
支持语音消息。

### CODE REVIEW

**Comment by tonyseek** [comment]
LGTM.

Would you like to cover it with testing and document (in README)?

**Comment by xtao** [comment]
@tonyseek ping

**Comment by lepture** [comment]
LGTM @VeryCB

**Comment by tonyseek** [comment]
:clap:

**Comment by tonyseek** [comment]
released [0.5.0](https://pypi.python.org/pypi/Flask-Weixin/0.5.0)

**Comment by VeryCB** [comment]
LGTM

**Pull request merged**
