### PR TITLE
A bit improvement.

### PR DESCRIPTION
**Pull request by tonyseek**
### Changes

- Capture exceptions explicitly instead of `except:` all.
- Use list comprehension instead of `lambda` + `map`.

@lepture @VeryCB Please review. Thanks.

### CODE REVIEW

**Comment by VeryCB** [comment]
@tonyseek UT is failed...seems a 'SyntaxError` is raised if the request body is invalid.

**Comment by tonyseek** [comment]
@VeryCB The `lxml` is using a built-in exception here. TAT

**Comment by VeryCB** [comment]
lgtm

**Comment by lepture** [comment]
LGTM. merge

**Pull request merged**
